AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  server

Globals:
  Function:
    Timeout: 5

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: AWS Api Gateway
      StageName: Staging
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Lambda:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /categories/{category}
            Method: get

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaFunctionRole.Arn
